### ISSUE TITLE
Questions about the segmentation experiment

### ISSUE THREAD

**Issue by zoomkinseok** [czq142857/BSP-NET-pytorch#11]
Hi,
Thanks for sharing your good research.
In the segmentation experiment, you said that for each point sample, label is assigned by measuring the distance among nearby primitives. Is there a code for this in your repo?

**Comment by czq142857** [comment]
That portion of the code has never been cleaned, therefore it is messy and not included in this repo. It is not hard to implement so you can implement it yourself, or you can email me and I will send you the code.
