### ISSUE TITLE
SVR training with RGB images

### ISSUE THREAD

**Issue by ismaelePiparo** [czq142857/BSP-NET-pytorch#13]
Hi,

I am interested in testing your code with different resolution RGB images. It is possible to use "modelSVR.py" also with RGB images? What changes need to be made?
As for the resolution of the images, is it necessary to add other levels of convolution?

**Comment by czq142857** [comment]
Of course. Just modify the code to read your images.

The testing code is using images in the testing set, as below.
```
batch_view = self.data_pixels[t:t+1,self.test_idx].astype(np.float32)/255.0
```

Now you can replace that with an image loader
```
batch_view = cv2.imread("example.jpg", cv2.IMREAD_GRAYSCALE)
batch_view = cv2.resize(batch_view, (128,128)).astype(np.float32)/255.0
batch_view = np.reshape(batch_view, [1,1,128,128])
```

But keep in mind that the pretrained model is pretty much overfitted to the ShapeNet dataset. So your image needs to be similar in style to the training images for the pretrained model to work,

**Comment by ismaelePiparo** [comment]
Hi, thanks for the reply!

I have another question. In "modelSVR.py", what do "ef_dim" and "img_ef_dim" mean and what are their effects?

I'm sorry but I'm a beginner with neural networks!

**Comment by czq142857** [comment]
"ef_dim" determines the number of neurons in each layer of the MLP.
"img_ef_dim" determines the number of channels in each layer of the 2D CNN.
You can read the code and search these two terms for a better understanding.
