### ISSUE TITLE
Normalizing meshes

### ISSUE THREAD

**Issue by elmiraloo** [czq142857/BSP-NET-pytorch#15]
Hi, 

Thanks for sharing this code. What do you use to normalize the meshes prior to making voxels? Did you write your own python script like this (http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v2-old/shapenet/scripts/shapenetcorev2/normalize.py) or do you suggest other tools that potentially can make things faster?

**Comment by czq142857** [comment]
Normalizing meshes is probably the least time-consuming part of the entire pipeline. I don't think you could make it faster. I do have [my own script](https://github.com/czq142857/DECOR-GAN/blob/main/data_preparation/1_simplify_obj.py). It is doing the same thing as the script you shared from shapenetcorev2.

**Comment by elmiraloo** [comment]
thanks!
