### ISSUE TITLE
How many model I need for training AE

### ISSUE THREAD

**Issue by ismaelePiparo** [czq142857/BSP-NET-pytorch#16]
Hi,
If I want to train the Autoencoder from scratch with my 3d models, how many models do I need?

Thanks in advance for your reply

**Comment by czq142857** [comment]
It depends on your task. One shape is sufficient if you just want to overfit. You can also apply data augmentation to get more training shapes.

**Comment by ismaelePiparo** [comment]
Thanks for the reply,
Data augmentation must be done before AE training (when creating the hdf5 file with voxels and point sampling) or there is a script that implements it during training.

**Comment by czq142857** [comment]
Data augmentation is not compulsory, so you can apply it when you really need it. The provided code does not contain data augmentation. If you do need it, please implement it yourself.
