### ISSUE TITLE
About texture

### ISSUE THREAD

**Issue by YuQiao0303** [czq142857/BSP-NET-pytorch#18]
Hi! Thank you so much for this wonderful work.

I'm interested in applying textures on the output meshes, as shown in the paper. The textures seem continuous across different convexes. May I ask how do you do the UV mapping to apply the textures please? Thank you!

**Comment by czq142857** [comment]
I was using a procedural wood texture so a UV map is not needed.

You can search "procedural texture" and "solid texturing" to learn more.

You can also use Blender to automatically generate a UV map if you really need one.

**Comment by YuQiao0303** [comment]
> I was using a procedural wood texture so a UV map is not needed.
> 
> You can search "procedural texture" and "solid texturing" to learn more.
> 
> You can also use Blender to automatically generate a UV map if you really need one.

I see. Thank you!
