### ISSUE TITLE
SVR from RGB image input using pretrained model

### ISSUE THREAD

**Issue by athenas-lab** [czq142857/BSP-NET-pytorch#4]
Hi,

Thank you for making the code available publicly. I am interested in using your pretrained model to reconstruct 3D mesh from an RGB image (for testing). The BSP_SVR class in modelSVR.py has a method test_mesh_obj_material() that generates a 3D mesh with color/material in .obj format, which is the format I need. Can this method be used to reconstruct mesh directly from an image input? This method requires pixel data (self.data_pixels) as input in the following line of code.
           for t in range(config.start, min(len(self.data_pixels),config.end))

In your code, self.data_pixels is extracted from the hdf5 files. For new test images for which we dont have the hdf5 files, could you please let us know what kind of data processing we need to do to  define self.data_pixels from an RGB image input? 

thanks

**Comment by czq142857** [comment]
Hi,

Essentially you need to input a 1x1x128x128 tensor to the network, which is a gray-scale image with a **white background**.

Please refer to function *test_image* in this file for how to prepare such a tensor: https://github.com/czq142857/IM-NET/blob/master/IMSVR/model.py

Note that if your input is a png with alpha channels, the image background may be black, and you need to fill the background with white with respect to the alpha channels.

Best,
Zhiqin

**Comment by athenas-lab** [comment]
Hi,
Thank you for the response. Attached text file shows the pytorch code for reconstructing a mesh from an image using a pretrained BSP-Net model (in case some one else needs it).  It has been modified from the BSP_SVR class in the original code. The attached graphic shows the 3D reconstruction  from an online image using the pretrained BSP-Net  pytorch model  available on this github repository. 

[test_img_bsp_svr.txt](https://github.com/czq142857/BSP-NET-pytorch/files/5363757/test_img_bsp_svr.txt)
![bsp](https://user-images.githubusercontent.com/12867837/95720847-9c917100-0c26-11eb-9be4-f3697c1de56c.png)
